### ISSUE TITLE
code tidak sesuai

### ISSUE THREAD

**Issue by aqmarinas** [Fasther1/progress_tugas#1]
terdapat beberapa file yang masih belum sesuai:

- file create_product_table.php belum dimodifikasi. mohon buka kembali modul bab 3 dan lakukan modifikasi sesuai instruksi.
- routes dan controller belum dihubungkan (modul bab 4).
- controller dan view juga belum dihubungkan (modul bab 4).

**Comment by Fasther1** [comment]
udah bener blum teh ?

**Comment by aqmarinas** [comment]
blm. tolong ikutin sesuai modul ya. itu bakal kepake lagi di pertemuan-pertemuan berikutnya.

untuk commit messagenya. tuliskan perubahan yang dilakukan di bagian mana

kalo masih belum paham, pc aja.
